inventory/urls.py
from django.urls import include, path

from .views import *

app_name ='stocks'

urlpatterns = [
    path('login/',login_page,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register',register_page),
    path('',AdminHomeView.as_view(), name='home'),
    
    # Purchase source CRUD
    path('purchasesource/',PurchasesourceListView.as_view(),name='purchasesource'),
    path('purchasesourcedetail/',PurchasesourceDetailView.as_view(),name='purchasesourcedetail'),
    path('purchase-source_update/<int:pk>/',PurchaseSourceUpdateView.as_view(), name='purchase-source_update'),
    path('purchasesource-deleted/', PurchaseSourceDeletedListView.as_view(), name='purchasesource_deleted'),
    path('purchasesource-restore/<int:pk>/', restore_purchasesource, name='restore_purchasesource'),
    
    
    path('stocks/',GoldStockListView.as_view(),name='goldstocks'),
    path('stocks/create',StockCreateView.as_view(),name='stock-create'),
    path('stock_update/<int:pk>/',StockUpdateView.as_view(), name='stock_update'),
    path('deleted/', StockDeletedListView.as_view(), name='stocks_deleted'),
    path('stock-restore/<int:pk>/', restore_stock, name='restore_stock'),
    
    path('stockornament/',GoldOrnamentListView.as_view(),name='ornamentstock'),
    path('stockornaments/create',StockOrnamentCreateView.as_view(),name='stockornament-create'),
    
    path('ornaments-count/',OrnamentCountView.as_view(),name='ornamentscount'),
    path('ornaments/',OrnamentListView.as_view(),name='ornaments'),
    path('ornaments/create',OrnamentCreateView.as_view(),name='ornament-create'),
    path('sales-ornaments/create',SalesOrnamentCreateView.as_view(),name='sales-ornament-create'),
    path('ornament_update/<int:pk>/',OrnamentUpdateView.as_view(), name='ornament_update'),
    path('ornamentdeleted/', OrnamentDeletedListView.as_view(), name='ornaments_deleted'),
    path('ornament-restore/<int:pk>/', restore_ornament, name='restore_ornament'),
]

jewellers/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    # path('',include('inventory.urls',namespace='inventory')),
    path('',include('inventory.urls')),
    path('',include('sales.urls')),
    path('',include('transaction.urls')),
    path('',include('investment.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import include, path

from .views import *
from .views import convert_orders_to_sales
app_name ='sales'

urlpatterns = [
    path('orders/',OrderView.as_view(),name='order'),
    path('order/create',OrderCreateView.as_view(),name='search_ornaments'),
    path('order/create',OrderCreateView.as_view(),name='order-create'),
    path('order_update/<int:pk>/',OrderUpdateView.as_view(), name='order_update'),
    path('sales/',SalesView.as_view(),name='sales'),
    path('sales/create',SalesCreateView.as_view(),name='sales-create'),
    path('sales_update/<int:pk>/',SalesUpdateView.as_view(), name='sales_update'),
    path('convert_order_to_sales/<int:order_id>/', convert_orders_to_sales, name='convert_order_to_sales'),
    # path('deleted/', StockDeletedListView.as_view(), name='sales_deleted'),
    # path('restore/<int:pk>/', restore_stock, name='restore_sales'),

]

templates/ornaments/add_ornament.html
<!-- The Modal -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Add {{ model_name }}</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
  
        <!-- Modal body -->
        <div class="modal-body">
  
            
  <form method="POST" class="card-body" enctype="multipart/form-data">
    {% csrf_token %}
  
  {% for field in form %}
  {{ field.errors }}
      <div class="fieldWrapper">
          <div class="form-group">
          {{ field.label_tag }} {{ field }}
          </div>
      </div>
  {% endfor %}
  
  <button type="submit" class="btn btn-primary">Save</button>
  </form>
  
  
  
        </div>
  
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
  
      </div>
    </div>
  </div>
  

templates/ornaments/deleted.html
{% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}
        <div class="main-panel">
          <div class="content-wrapper">
          
            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">{{ title }}</h4>

              <div class="btn-group" role="group" aria-label="Stock">
                <a href="{% url 'stocks:ornaments' %}" class="btn btn-secondary {% if not stock %}active{% endif %}">All Ornaments</a>
            </div>

                    <div class="table-responsive">
                      <table class="table">
                        <thead>
                          <tr style="color:white">
                            <th>Actions</th>
                            <th> Product name </th>
                            <th> Weight</th>
                            <th> Jarti</th>
                            <th> Total weight</th>
                            <th> Rate(10 gram) </th>
                            <th> Wages </th>
                            <th> Stones </th>
                            <th> Total </th>
                            <th> Payed </th>
                            <th> Due </th>
                            <th> Payment method</th>
                            <th> Purchased from</th>
                            <th> Pan</th>
                            <th> Purchased date </th>
                            <th> Status </th>
                          </tr>
                        </thead>
                        <tbody>
              
                        
                          {% for item in deleted_ornaments %}
                            <tr>
                              <td>
                                <a onclick="deleteItem(this)" data-id="{{ item.id }}" class="btn btn-danger">Permanently Delete</a>
                                <a href="{% url 'stocks:restore_ornament' item.id %}" class="btn btn-success">Restore</a>

                              </td>
                              <td>
                                <span class="pl-2">{{ item.product_name }}</span>
                              </td>
                              <td> {{ item.weight|floatformat:2 }} </td>
                              <td> {{ item.jarti|floatformat:2 }} </td>
                              <td> {{ item.total_weight|floatformat:2 }} </td>
                              <td> {{ item.rate|floatformat:0 }} </td>
                              <td> {{ item.wages|floatformat:0 }} </td>
                              <td> {{ item.stones|floatformat:0 }} </td>
                              <td> {{ item.grand_total|floatformat:2 }} </td>
                              <td> {{ item.cash|floatformat:2 }} </td>
                              <td> {{ item.bank|floatformat:2 }} </td>
                              <td>{{ item.due }}</td>
                              <td> {{ item.purchased_from }} </td>
                              <td> {{ item.pan|floatformat:2 }} </td>
                              <td> {{ item.Nepali_date }} </td>

                              {% if item.status == 'approved' %}
                              <td>
                                <div class="badge badge-outline-success">{{ item.status }} </div>
                              </td>
                              
                              {% else %}
                              <td>
                                <div class="badge badge-outline-danger">{{ item.status }} </div>
                              </td>
                              {% endif %}
                            </tr>

                            {% empty%}
                            <tr>
                                <td colspan="4">No stocks found.</td>
                            </tr>

                            {% endfor %}
                          
                            {% if ornaments %}
                            <tr style="color:white">
                              <td>Total Weight</td>
                              <td colspan="1"></th>
                              <td>{{ totalweight|floatformat:2 }}</td>
                              <td colspan="5"></th>
                              <td>{{ total|floatformat:0 }}</td>
                              <td>{{ paid|floatformat:0 }}</td>
                              <td>{{ due|floatformat:0 }}</td>
                              <td colspan="5"></th>
                            </tr>

                        {% endif %}
                          </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>

          {% include 'footer.html' %}

          <!-- partial -->
        </div>

    {% endblock %}

templates/ornaments/detail.html
{% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}
        <div class="main-panel">
          <div class="content-wrapper">

            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                    <h1>{{ object.Purchased_from }}</h1>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->

          {% include 'footer.html' %}

          <!-- partial -->
        </div>

    {% endblock %}
  </body>
</html>

templates/ornaments/ornament_create.html
{% extends 'basic.html' %}
{% load static %}


{% block body %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">       
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add</h4>

                            <!-- Button to Open the Modal -->
          
                        <form method="POST" class="card-body" enctype="multipart/form-data">
                            {% csrf_token %}
                          
                            <div class="row">
                                {% for field in form %}
                                
                                {{ field.errors }}
                                    <div class="fieldWrapper col-6">
                                        <div class="form-group">
                                        {{ field.label_tag }} {{ field }}
                                        </div>
                                    </div>
                                  
                                {% endfor %}
                              </div>
                          
                        
                          <button type="submit" class="btn btn-primary">Save Ornament</button>
                          </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'include/add_model.html' %}
    {% include 'footer.html' %}
</div>
{% endblock %}

templates/ornaments/ornament_update.html
{% extends 'basic.html' %}
{% load static %}


{% block body %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">       
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Update</h4>

                            <form method="POST" action="{% url 'stocks:ornament_update' pk=object.pk %}">
                                {% csrf_token %}
                                <div class="row">
                                    {% for field in form %}
                                    
                                    {{ field.errors }}
                                        <div class="fieldWrapper col-6">
                                            <div class="form-group">
                                            {{ field.label_tag }} {{ field }}
                                            </div>
                                        </div>
                                      
                                    {% endfor %}
                                  </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


    {% include 'footer.html' %}
</div>
{% endblock %}

templates/ornaments/ornaments.html
{% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}
  <div class="main-panel">
    <div class="content-wrapper">

      <div class="row">
        <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">

              <div class="row">
                <div class="col-9">
                  <div class="d-flex align-items-center align-self-start">
                    <h3 class="mb-0">{{ weight|floatformat:2 }} gram</h3>
                      <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                  </div>

                </div>

                <div class="col-3">
                  <div class="icon icon-box-success ">
                    <span class="mdi mdi-arrow-top-right icon-item"></span>
                  </div>
                </div>
              </div>

                <h6 class="text-muted font-weight-normal">Stock Ornaments Gold</h6>
            </div>
          </div>
        </div>

        <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-9">
                  <div class="d-flex align-items-center align-self-start">
                    <h3 class="mb-0">Rs. {{ total|floatformat:0 }}</h3>
                    <p class="text-success ml-2 mb-0 font-weight-medium">+11%</p>
                  </div>
                </div>

                <div class="col-3">
                  <div class="icon icon-box-success">
                    <span class="mdi mdi-arrow-top-right icon-item"></span>
                  </div>
                </div>

              </div>
              <h6 class="text-muted font-weight-normal">Ornaments Stock</h6>
            </div>
          </div>
        </div>

        <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-9">
                  <div class="d-flex align-items-center align-self-start">
                    <h3 class="mb-0">{{ ornaments_count }}</h3>
                    <p class="text-danger ml-2 mb-0 font-weight-medium">-2.4%</p>
                  </div>
                </div>

                <div class="col-3">
                  <div class="icon icon-box-danger">
                    <span class="mdi mdi-arrow-bottom-left icon-item"></span>
                  </div>
                </div>

              </div>
              <h6 class="text-muted font-weight-normal">Total Oraments</h6>
            </div>
          </div>
        </div>

        <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="row">
                <div class="col-9">
                  <div class="d-flex align-items-center align-self-start">
                    <h3 class="mb-0">$31.53</h3>
                    <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                  </div>
                </div>

                <div class="col-3">
                  <div class="icon icon-box-success ">
                    <span class="mdi mdi-arrow-top-right icon-item"></span>
                  </div>
                </div>

              </div>
              <h6 class="text-muted font-weight-normal">Expense current</h6>
            </div>
          </div>
        </div>
      </div>
          
      <div class="row ">
        <div class="col-12 grid-margin">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Upload Ornament File</h4>
             
              <div class="opload-form">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {{ ornament_upload_form.non_field_errors }}
                  <div class="row">
                    {% if message %}
                      <div class="text-danger">
                        <span>{{ message }}</span><br>
                      </div>
                    {% endif %}
                  </div>
                        
                  <div class="form-group">
                    <div class="row">
                

                      <div class="col-3">
                        {{ ornament_upload_form.ornament_file }}
                      </div>

                      <div class="col-3">
                        {% if ornament_upload_form.ornament_file.errors %}
                          <div class="text-danger">
                          {% for error in ornament_upload_form.ornament_file.errors %}
                            <span>{{ error }}</span><br>
                          {% endfor %}
                          </div>
                        {% endif %}
                      </div>

                      <div class="col-3">
                        <button style="font-size:12px;" class="btn btn-success float-right" type="submit">Upload Ornaments</button>
                      </div>
                    </div>
                  </div>    
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  

      <div class="row ">
        <div class="col-12 grid-margin">
          <div class="card">
            <div class="card-body">

              <h4 class="card-title">Ornaments</h4>
   
              <div class="row mb-4">
                  <div class="col-md-6">
                      <form method="get" action="{% url 'stocks:ornaments' %}">
                          <div class="input-group">
                              <input class="form-control" type="text" name="search" placeholder="Search by ornament name">
                              <div class="input-group-append">
                                  <button class="btn btn-success" type="submit">Search</button>
                              </div>
                          </div>
                      </form>
                    </div>
      
    
           
                <div class="col-md-6">
                  <form method="get">
                    <div class="input-group">
                      <select class="form-control" id="main_category" name="main_category">
                        <option value="">All Categories</option>
                          {% for category in main_categories %}
                            <option value="{{ category.pk }}" {% if selected_category == category %}selected{% endif %}>{{ category.name }}</option>
                          {% endfor %}
                      </select>

                      <div class="input-group-append">
                        <button type="submit" class="btn btn-success">Filter</button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>

            
            

              <div class="btn-group" role="group" aria-label="STOCK">
                <a href="{% url 'stocks:ornaments' %}" class="btn btn-secondary {% if not stock %}active{% endif %}">All</a>
                <a href="{% url 'stocks:ornaments' %}?stock=ORDERED" class="btn btn-secondary {% if stock == 'ORDERED' %}active{% endif %}">Ordered</a>
                <a href="{% url 'stocks:ornaments' %}?stock=SOLD" class="btn btn-secondary {% if stock == 'SOLD' %}active{% endif %}">Sold</a>
                <a href="{% url 'stocks:ornaments' %}?stock=DESTROYED" class="btn btn-secondary {% if stock == 'DESTROYED' %}active{% endif %}">Destroyed</a>
                <a href="{% url 'stocks:ornaments_deleted' %}" class="btn btn-secondary">Deleted</a>
              </div>

              <a href="{% url 'stocks:ornament-create' %}" class="btn btn-primary float-right">Add New Ornament</a>
                    
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr style="color:white">
                        <th>Actions</th>
                        <th> Purchased date </th>
                        <th> Product name </th>
                        <th> Weight(gram) </th>
                        <th> Jarti</th>
                        <th> Total weight</th>
                        <th> Rate(Tola) </th>
                        <th> Wages </th>
                        <th> Stones </th>
                        <th> Total </th>
                        <th> Cash </th>
                        <th> Bank </th>
                        <th> Due </th>
                        <th> Purchased from</th>
                        <th> Kaligar</th>
                        
                      </tr>
                    </thead>

                    <tbody>
                      {% for item in ornaments %}
                        <tr>
                          <td>
                    
                            <a href="{% url 'stocks:ornament_update' item.pk %}" class="btn btn-primary" >edit</a>
                            <a onclick="deleteItem(this)" data-id="{{ item.id }}" class="btn btn-danger">delete</a>
                          </td>
                          <td> {{ item.nepali_date }} </td>
                          <td>
                            <span class="pl-2">{{ item.product_name }}</span>
                          </td>
                          <td> {{ item.weight|floatformat:3 }} </td>
                          <td> {{ item.jarti|floatformat:2 }} </td>
                          <td> {{ item.total_weight|floatformat:2 }} </td>
                          <td> {{ item.rate|floatformat:0 }} </td>
                          <td> {{ item.wages|floatformat:0 }} </td>
                          <td> {{ item.stones|floatformat:0 }} </td>
                          <td> {{ item.grand_total|floatformat:2 }} </td>
                          <td> {{ item.cash|floatformat:2 }} </td>
                          <td> {{ item.bank|floatformat:2 }} </td>
                          <td>{{ item.due|floatformat:0 }}</td>

                          {% if item.purchased_from.name %}
                            <td> {{ item.purchased_from.name }} </td>
                        
                          {% else %}
                            <td>-----</td>
                          {% endif %}

                          <td> {{ item.kaligar.name }} </td>

                            {% if item.status == 'approved' %}
                            <td>
                              <div class="badge badge-outline-success">{{ item.status }} </div>
                            </td>
                              
                            {% else %}
                              <td>
                                <div class="badge badge-outline-danger">{{ item.status }} </div>
                              </td>
                            {% endif %}


                        </tr>

                        {% empty%}
                        <tr>
                          <td colspan="4">No Ornaments found.</td>
                        </tr>
                      {% endfor %}
                          
                      {% if ornaments%}
                        <tr style="color:white">
                          <td>Total Weight</td>
                          <td colspan="2"></th>
                          <td>{{ weight|floatformat:2 }}</td>
                          <td>{{ totaljarti|floatformat:2 }}</td>
                          <td>{{ totalweight|floatformat:3 }}</td>
                          <td colspan="3"></th>
                          <td>{{ total|floatformat:0 }}</td>
                          <td colspan="6"></th>
                        </tr>
                      {% endif %}

                    </tbody>

                    
                  </table>
                </div>

                 <!-- Pagination -->
                 <div class="pagination mt-3">
                  <span class="step-links">
                      {% if ornaments.has_previous %}
                          <a href="?page=1">&laquo; first</a>
                          <a href="?page={{ ornaments.previous_page_number }}">previous</a>
                      {% endif %}
                      
                      <span class="current">
                          Page {{ ornaments.number }} of {{ ornaments.paginator.num_pages }}.
                      </span>
                      
                      {% if ornaments.has_next %}
                          <a href="?page={{ ornaments.next_page_number }}">next</a>
                          <a href="?page={{ ornaments.paginator.num_pages }}">last &raquo;</a>
                      {% endif %}
                  </span>
              </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      {% include 'footer.html' %}
  </div>

{% endblock %}

templates/ornaments/ornamentscount.html
{% extends 'basic.html' %}
{% load static %}

<!-- container-scroller -->
{% block body %}
<div class="main-panel">
  <div class="content-wrapper">
    <div class="row col-12 grid-margin">
       <button type="button"  class="btn btn-primary float-right mt-2" data-toggle="modal" data-target="#myModal"> Add new ornament</button>
    </div>
    <div class="row">
      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Available Ornaments</h4>
            <ul>
              {% for category in main_categories_with_counts %}
              <li><a style="color:white; padding-left:0; margin-left:0;" href="{% url 'stocks:ornaments' %}?main_category={{ category.pk }}">{{ category.name }} : ({{ category.count_ornaments }} ) - Rs {{ category.total_amount|floatformat:0 }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>

      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Ordered Ornaments</h4>
            <ul>

              {% for category in ordered_with_counts %}
              {% if category.count_ornaments > 0%}
              <li>{{ category.name }} ({{ category.count_ornaments }} ornaments)</li>
              {% endif %}
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>

  {% include 'footer.html' %}
  {% include 'include/add_model.html' %}
  <!-- partial -->
</div>
{% endblock %}