inventory/urls.py
from django.urls import include, path

from .views import *

app_name ='stocks'

urlpatterns = [
    path('login/',login_page,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register',register_page),
    path('',AdminHomeView.as_view(), name='home'),
    
    # Purchase source CRUD
    path('purchasesource/',PurchasesourceListView.as_view(),name='purchasesource'),
    path('purchasesourcedetail/',PurchasesourceDetailView.as_view(),name='purchasesourcedetail'),
    path('purchase-source_update/<int:pk>/',PurchaseSourceUpdateView.as_view(), name='purchase-source_update'),
    path('purchasesource-deleted/', PurchaseSourceDeletedListView.as_view(), name='purchasesource_deleted'),
    path('purchasesource-restore/<int:pk>/', restore_purchasesource, name='restore_purchasesource'),
    
    
    path('stocks/',GoldStockListView.as_view(),name='goldstocks'),
    path('stocks/create',StockCreateView.as_view(),name='stock-create'),
    path('stock_update/<int:pk>/',StockUpdateView.as_view(), name='stock_update'),
    path('deleted/', StockDeletedListView.as_view(), name='stocks_deleted'),
    path('stock-restore/<int:pk>/', restore_stock, name='restore_stock'),
    
    path('stockornament/',GoldOrnamentListView.as_view(),name='ornamentstock'),
    path('stockornaments/create',StockOrnamentCreateView.as_view(),name='stockornament-create'),
    
    path('ornaments-count/',OrnamentCountView.as_view(),name='ornamentscount'),
    path('ornaments/',OrnamentListView.as_view(),name='ornaments'),
    path('ornaments/create',OrnamentCreateView.as_view(),name='ornament-create'),
    path('sales-ornaments/create',SalesOrnamentCreateView.as_view(),name='sales-ornament-create'),
    path('ornament_update/<int:pk>/',OrnamentUpdateView.as_view(), name='ornament_update'),
    path('ornamentdeleted/', OrnamentDeletedListView.as_view(), name='ornaments_deleted'),
    path('ornament-restore/<int:pk>/', restore_ornament, name='restore_ornament'),
]

jewellers/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    # path('',include('inventory.urls',namespace='inventory')),
    path('',include('inventory.urls')),
    path('',include('sales.urls')),
    path('',include('transaction.urls')),
    path('',include('investment.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import include, path

from .views import *
from .views import convert_orders_to_sales
app_name ='sales'

urlpatterns = [
    path('orders/',OrderView.as_view(),name='order'),
    path('order/create',OrderCreateView.as_view(),name='search_ornaments'),
    path('order/create',OrderCreateView.as_view(),name='order-create'),
    path('order_update/<int:pk>/',OrderUpdateView.as_view(), name='order_update'),
    path('sales/',SalesView.as_view(),name='sales'),
    path('sales/create',SalesCreateView.as_view(),name='sales-create'),
    path('sales_update/<int:pk>/',SalesUpdateView.as_view(), name='sales_update'),
    path('convert_order_to_sales/<int:order_id>/', convert_orders_to_sales, name='convert_order_to_sales'),
    # path('deleted/', StockDeletedListView.as_view(), name='sales_deleted'),
    # path('restore/<int:pk>/', restore_stock, name='restore_sales'),

]

sales/forms.py
from django import forms
from django.contrib.auth import get_user_model
from nepali_datetime_field.forms import NepaliDateField
from inventory.models import Ornaments
from .models import Sales, Order, SelectedOrnament
import nepali_datetime
from django_select2.forms import Select2MultipleWidget

User=get_user_model()

class SalesUploadForm(forms.Form):
    sales_file = forms.FileField(label='Upload Sales File', widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))

    def clean_stock_file(self):
        sales_file = self.cleaned_data['sales_file']
        if sales_file:
            if not sales_file.name.endswith('.xlsx'):
                raise forms.ValidationError('Invalid file format. Please upload a valid Excel file.')
        return sales_file

class SearchOrnamentsWidget(Select2MultipleWidget):
    search_fields = [
        'product_name__icontains',
        'weight__icontains',
        'purity__icontains',
        'material__icontains',
    ]
      
          
class OrderForm(forms.ModelForm):
    selected_ornaments = forms.ModelMultipleChoiceField(
    queryset=SelectedOrnament.objects.filter(order_status='PROCESSING'),
    widget=SearchOrnamentsWidget(attrs={'style': 'width: 100%;'}),
    )

    class Meta:
        model = Order
        fields =['nepali_date','customer','address','phone_no','selected_ornaments','discounts','own_gold','cash','bank','due','notes']
        widgets = {
            'nepali_date': forms.DateInput(attrs={'class': 'form-control'}),
            'customer': forms.TextInput(attrs={'class': 'form-control','required': 'true'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_no': forms.TextInput(attrs={'class': 'form-control'}),
            'discounts': forms.TextInput(attrs={'class': 'form-control'}),
            'own_gold': forms.TextInput(attrs={'class': 'form-control'}),
            'cash': forms.TextInput(attrs={'class': 'form-control'}),
            'bank': forms.TextInput(attrs={'class': 'form-control'}),
            'due': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control'}),
        }
        date:NepaliDateField()   


    def label_from_instance(self, obj):
            return f"{obj.product_name} - Weight: {obj.weight} - Purity: {obj.purity} - Material: {obj.material}"    
     
     
    def __init__(self,*args,**kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        nepali_date=nepali_datetime.date.today()
        self.fields['nepali_date'].initial = nepali_date


class selectedOrnamentForm(forms.ModelForm):

    class Meta:
        model=SelectedOrnament
        fields=['ornament','rate','jarti','jyala','stone']
        widgets={
            'ornament': forms.Select(attrs={'class': 'form-control col-12'}),
            'rate': forms.TextInput(attrs={'class': 'form-control'}),
            'jarti': forms.TextInput(attrs={'class': 'form-control'}),
            'jyala': forms.TextInput(attrs={'class': 'form-control'}),
            'stone': forms.TextInput(attrs={'class': 'form-control'}),
        }
   
    def __init__(self, *args, **kwargs):
        super(selectedOrnamentForm, self).__init__(*args, **kwargs)
        
        # Modify the queryset for the 'ornament' field to only show available ornaments
        available_ornaments = Ornaments.objects.filter(stock='AVAILABLE').order_by('product_name')  # Adjust the filter criteria as needed
        self.fields['ornament'].queryset = available_ornaments
    
class SalesForm(forms.ModelForm):
    
    selected_ornaments = forms.ModelMultipleChoiceField(
    queryset=SelectedOrnament.objects.filter(order_status='PROCESSING'),
    widget=SearchOrnamentsWidget(attrs={'style': 'width: 100%;'}),
    )
    
    class Meta:
        model = Sales
        fields = ['bill_no','nepali_date','customer','address','phone_no','selected_ornaments','own_gold','discounts','total_weight','grand_total','profit','cash','bank','due','notes']
        widgets = {
            'bill_no': forms.TextInput(attrs={'class': 'form-control'}),
            'nepali_date': forms.DateInput(attrs={'class': 'form-control'}),
            'customer': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_no': forms.TextInput(attrs={'class': 'form-control'}),
            'discounts': forms.TextInput(attrs={'class': 'form-control'}),
            'own_gold': forms.TextInput(attrs={'class': 'form-control'}),
            'cash': forms.TextInput(attrs={'class': 'form-control'}),
            'bank': forms.TextInput(attrs={'class': 'form-control'}),
            'due': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control'}),
            'total_weight': forms.TextInput(attrs={'class': 'form-control'}),
            'grand_total': forms.TextInput(attrs={'class': 'form-control'}),
            'profit': forms.TextInput(attrs={'class': 'form-control'}),
        }
        date:NepaliDateField()
        
    def label_from_instance(self, obj):
            return f"{obj.product_name} - Weight: {obj.weight} - Purity: {obj.purity} - Material: {obj.material}"
        
    def __init__(self,*args,**kwargs):
        super(SalesForm, self).__init__(*args, **kwargs)
        nepali_date=nepali_datetime.date.today()
        self.fields['nepali_date'].initial = nepali_date

        



templates/stocks/detail.html
{% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}
        <div class="main-panel">
          <div class="content-wrapper">

            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                    <h1>{{ object.Purchased_from }}</h1>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->

          {% include 'footer.html' %}

          <!-- partial -->
        </div>

    {% endblock %}
  </body>
</html>

templates/stocks/stock_update.html
{% extends 'basic.html' %}
{% load static %}


{% block body %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">       
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Update</h4>

                            <form method="POST" action="{% url 'stocks:stock_update' pk=object.pk %}">
                               
                                {% csrf_token %}

                                <div class="row">
                                    {% for field in form %}
                          
                          {{ field.errors }}
                              <div class="fieldWrapper col-6">
                                  <div class="form-group">
                                  {{ field.label_tag }} {{ field }}
                                  </div>
                              </div>
                            
                          {% endfor %}
                                </div>
                            
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


    {% include 'footer.html' %}
</div>
{% endblock %}

templates/stocks/stockornaments.html
{% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}

        <div class="main-panel">
          <div class="content-wrapper" >


            <div class="row">
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ totalweight|floatformat:2 }} gram</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success ">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Stock Gold</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ pure_gold|floatformat:2 }} gram</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+11%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">24-carat Gold</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ mix_gold}} gram</h3>
                          <p class="text-danger ml-2 mb-0 font-weight-medium">-2.4%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-danger">
                          <span class="mdi mdi-arrow-bottom-left icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Mix Gold</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">Rs.{{ total|floatformat:0 }}</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success ">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Stock</h6>
                  </div>
                </div>
              </div>
            </div>
          
          

                    <div class="row ">
                      <div class="col-12 grid-margin">
                        <div class="card">
                          <div class="card-body">
                            <h4 class="card-title">Stock Ornamens</h4>

              <a  href="{% url 'stocks:stockornament-create' %}" class="btn btn-primary float-right mb-2">Add New Stock</a>
            

              <div class="btn-group" role="group" aria-label="Purchased From">
                <a href="{% url 'stocks:goldstocks' %}" class="btn btn-secondary {% if not purchased_from %}active{% endif %}">All</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Bank" class="btn btn-secondary {% if purchased_from == 'Bank' %}active{% endif %}">Bank</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Shops" class="btn btn-secondary {% if purchased_from == 'Shops' %}active{% endif %}">Shops</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Customer" class="btn btn-secondary {% if purchased_from == 'Customer' %}active{% endif %}">Customer</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Vendor" class="btn btn-secondary {% if purchased_from == 'Vendor' %}active{% endif %}">Vendor</a>
                <a href="{% url 'stocks:stocks_deleted' %}" class="btn btn-secondary">Deleted</a>
            </div>

                    <div class="table-responsive">
                      <table class="table"> 
                        <thead>
                          <tr style="color:white">
                            <th>Actions</th>
                            <th> Date</th>
                            <th> Name </th>
                            <th> Weight(gram) </th>
                            <th> Rate(Tola) </th>
                            <th> Total </th>
                            <th> Cash </th>
                            <th> Bank </th>
                            <th> Due </th>
                            <th> Status </th>
                          </tr>
                        </thead>
                        <tbody>
              
                        
                          {% for item in stockornaments %}
                            <tr>
                              <td>
                    
                                <a href="{% url 'stocks:stock_update' item.pk %}" class="btn btn-primary" >edit</a>
                                  <a onclick="deleteItem(this)" data-id="{{ item.id }}" class="btn btn-danger">delete</a>
                              </td>
                              <td>{{ item.nepali_date }}</td>
                              <td>
                                <span class="pl-2">{{ item.purchase_source.name }}</span>
                              </td>
                              <td> {{ item.total_weight|floatformat:2 }} </td>
                              <td> {{ item.rate|floatformat:0 }} </td>
                              <td> {{ item.grand_total|floatformat:2 }} </td>
                              <td> {{ item.cash|floatformat:2 }} </td>
                              <td> {{ item.bank|floatformat:2 }} </td>
                              <td> {{ item.due|floatformat:2 }} </td>

                              {% if item.status == 'approved' %}
                              <td>
                                <div class="badge badge-outline-success">{{ item.status }} </div>
                              </td>
                              
                              {% else %}
                              <td>
                                <div class="badge badge-outline-danger">{{ item.status }} </div>
                              </td>
                              {% endif %}
                            </tr>

                            {% empty%}
                            <tr>
                                <td colspan="4">No stocks found.</td>
                            </tr>

                            {% endfor %}
                          
                            {% if stocks%}
                            <tr style="color:white">
                              <td>Total Weight</td>
                              <td colspan=2""></th>
                              <td>{{ totalweight|floatformat:2 }}</td>
                              <td></td>
                              <td>{{ total|floatformat:0 }}</td>
                              <td>{{ paid|floatformat:0 }}</td>
                              <td>{{ due|floatformat:0 }}</td>
                              <td colspan=3""></th>
                            </tr>

                        {% endif %}
                          </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>


          {% include 'footer.html' %}

          <!-- partial -->
        </div>

    {% endblock %}

templates/stocks/stocks.html
 {% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}

        <div class="main-panel">
          <div class="content-wrapper" >


            <div class="row">
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ totalweight|floatformat:2 }} gram</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success ">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Stock Gold</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ pure_gold|floatformat:2 }} gram</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+11%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">24-carat Gold</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ mix_gold}} gram</h3>
                          <p class="text-danger ml-2 mb-0 font-weight-medium">-2.4%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-danger">
                          <span class="mdi mdi-arrow-bottom-left icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Mix Gold</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">Rs.{{ total|floatformat:0 }}</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success ">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Stock</h6>
                  </div>
                </div>
              </div>
            </div>
          
            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title"> Upload Stock</h4>
             
                    

                    <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{ stock_upload_form.non_field_errors }}
                      <div class="row">
                        {% if message %}
                              <div class="text-danger">
                                  <span>{{ message }}</span><br>
                              </div>
                        {% endif %}
                      </div>
                      
                      <div class="form-group">
                        <div class="row">

                          <div class="col-3">
                            {{ stock_upload_form.stock_file }}
                          </div>

                          <div class="col-3">
                            {% if stock_upload_form.stock_file.errors %}
                              <div class="text-danger">
                                {% for error in stock_upload_form.stock_file.errors %}
                                    <span>{{ error }}</span><br>
                                {% endfor %}
                              </div>
                            {% endif %}
                          </div>

                          <div class="col-3">
                            <button style="font-size:12px;" class="btn btn-success float-right" type="submit">Upload</button>
                          </div>

                        </div>
                      </div>    
                    </form>
                  
                  </div>
                </div>
              </div>
            </div>
                    <div class="row ">
                      <div class="col-12 grid-margin">
                        <div class="card">
                          <div class="card-body">
                            <h4 class="card-title">Stocks</h4>

              <a  href="{% url 'stocks:stock-create' %}" class="btn btn-primary float-right mb-2">Add New Stock</a>
            

              <div class="btn-group" role="group" aria-label="Purchased From">
                <a href="{% url 'stocks:goldstocks' %}" class="btn btn-secondary {% if not purchased_from %}active{% endif %}">All</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Bank" class="btn btn-secondary {% if purchased_from == 'Bank' %}active{% endif %}">Bank</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Shops" class="btn btn-secondary {% if purchased_from == 'Shops' %}active{% endif %}">Shops</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Customer" class="btn btn-secondary {% if purchased_from == 'Customer' %}active{% endif %}">Customer</a>
                <a href="{% url 'stocks:goldstocks' %}?purchased_from=Vendor" class="btn btn-secondary {% if purchased_from == 'Vendor' %}active{% endif %}">Vendor</a>
                <a href="{% url 'stocks:stocks_deleted' %}" class="btn btn-secondary">Deleted</a>
            </div>

                    <div class="table-responsive">
                      <table class="table"> 
                        <thead>
                          <tr style="color:white">
                            <th>Actions</th>
                            <th> Date</th>
                            <th> Name </th>
                            <th> Weight(gram) </th>
                            <th> Rate(Tola) </th>
                            <th> Total </th>
                            <th> Cash </th>
                            <th> Bank </th>
                            <th> Due </th>
                            <th> Status </th>
                          </tr>
                        </thead>
                        <tbody>
              
                        
                          {% for item in stocks %}
                            <tr>
                              <td>
                    
                                <a href="{% url 'stocks:stock_update' item.pk %}" class="btn btn-primary" >edit</a>
                                  <a onclick="deleteItem(this)" data-id="{{ item.id }}" class="btn btn-danger">delete</a>
                              </td>
                              <td>{{ item.Nepali_date }}</td>
                              <td>
                                <span class="pl-2">{{ item.Purchase_source.name }}</span>
                              </td>
                              <td> {{ item.Total_weight|floatformat:2 }} </td>
                              <td> {{ item.Rate|floatformat:0 }} </td>
                              <td> {{ item.Grand_total|floatformat:2 }} </td>
                              <td> {{ item.Cash|floatformat:2 }} </td>
                              <td> {{ item.Bank|floatformat:2 }} </td>
                              <td> {{ item.Due|floatformat:2 }} </td>

                              {% if item.status == 'approved' %}
                              <td>
                                <div class="badge badge-outline-success">{{ item.status }} </div>
                              </td>
                              
                              {% else %}
                              <td>
                                <div class="badge badge-outline-danger">{{ item.status }} </div>
                              </td>
                              {% endif %}
                            </tr>

                            {% empty%}
                            <tr>
                                <td colspan="4">No stocks found.</td>
                            </tr>

                            {% endfor %}
                          
                            {% if stocks%}
                            <tr style="color:white">
                              <td>Total Weight</td>
                              <td colspan=2""></th>
                              <td>{{ totalweight|floatformat:2 }}</td>
                              <td></td>
                              <td>{{ total|floatformat:0 }}</td>
                              <td>{{ paid|floatformat:0 }}</td>
                              <td>{{ due|floatformat:0 }}</td>
                              <td colspan=3""></th>
                            </tr>

                        {% endif %}
                          </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>


          {% include 'footer.html' %}

          <!-- partial -->
        </div>

    {% endblock %}