inventory/urls.py
from django.urls import include, path

from .views import *

app_name ='stocks'

urlpatterns = [
    path('login/',login_page,name='login'),
    path('logout/',logout_view,name='logout'),
    path('register',register_page),
    path('',AdminHomeView.as_view(), name='home'),
    
    # Purchase source CRUD
    path('purchasesource/',PurchasesourceListView.as_view(),name='purchasesource'),
    path('purchasesourcedetail/',PurchasesourceDetailView.as_view(),name='purchasesourcedetail'),
    path('purchase-source_update/<int:pk>/',PurchaseSourceUpdateView.as_view(), name='purchase-source_update'),
    path('purchasesource-deleted/', PurchaseSourceDeletedListView.as_view(), name='purchasesource_deleted'),
    path('purchasesource-restore/<int:pk>/', restore_purchasesource, name='restore_purchasesource'),
    
    
    path('stocks/',GoldStockListView.as_view(),name='goldstocks'),
    path('stocks/create',StockCreateView.as_view(),name='stock-create'),
    path('stock_update/<int:pk>/',StockUpdateView.as_view(), name='stock_update'),
    path('deleted/', StockDeletedListView.as_view(), name='stocks_deleted'),
    path('stock-restore/<int:pk>/', restore_stock, name='restore_stock'),
    
    path('stockornament/',GoldOrnamentListView.as_view(),name='ornamentstock'),
    path('stockornaments/create',StockOrnamentCreateView.as_view(),name='stockornament-create'),
    
    path('ornaments-count/',OrnamentCountView.as_view(),name='ornamentscount'),
    path('ornaments/',OrnamentListView.as_view(),name='ornaments'),
    path('ornaments/create',OrnamentCreateView.as_view(),name='ornament-create'),
    path('sales-ornaments/create',SalesOrnamentCreateView.as_view(),name='sales-ornament-create'),
    path('ornament_update/<int:pk>/',OrnamentUpdateView.as_view(), name='ornament_update'),
    path('ornamentdeleted/', OrnamentDeletedListView.as_view(), name='ornaments_deleted'),
    path('ornament-restore/<int:pk>/', restore_ornament, name='restore_ornament'),
]

investment/urls.py
from django.urls import include, path

from .views import *

app_name ='investmentsandexpenses'

urlpatterns = [
    path('investments/', InvestmentListView.as_view(), name='investments'),
    path('investment/<int:pk>/',InvestmentUpdateView.as_view(), name='investment-update'),
    path('capital/', CaptalListView.as_view(), name='capital'),
    path('capital/<int:pk>/',CapitalUpdateView.as_view(), name='capital-update'),
    path('expenses/', ExpensesListView.as_view(), name='expenses'),
    path('expenses/<int:pk>/',ExpenseUpdateView.as_view(), name='expense-update'),
    path('summary/', SummaryListView.as_view(), name='summary'),
]

jewellers/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    # path('',include('inventory.urls',namespace='inventory')),
    path('',include('inventory.urls')),
    path('',include('sales.urls')),
    path('',include('transaction.urls')),
    path('',include('investment.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import include, path

from .views import *
from .views import convert_orders_to_sales
app_name ='sales'

urlpatterns = [
    path('orders/',OrderView.as_view(),name='order'),
    path('order/create',OrderCreateView.as_view(),name='search_ornaments'),
    path('order/create',OrderCreateView.as_view(),name='order-create'),
    path('order_update/<int:pk>/',OrderUpdateView.as_view(), name='order_update'),
    path('sales/',SalesView.as_view(),name='sales'),
    path('sales/create',SalesCreateView.as_view(),name='sales-create'),
    path('sales_update/<int:pk>/',SalesUpdateView.as_view(), name='sales_update'),
    path('convert_order_to_sales/<int:order_id>/', convert_orders_to_sales, name='convert_order_to_sales'),
    # path('deleted/', StockDeletedListView.as_view(), name='sales_deleted'),
    # path('restore/<int:pk>/', restore_stock, name='restore_sales'),

]

transaction/urls.py
from django.urls import include, path

from .views import *

app_name ='transaction'

urlpatterns = [
    path('transactions/',TransactionListView.as_view(),name='transaction'),
    path('kaligarornaments/<int:pk>/',KaligarornamentsListView.as_view(),name='kaligarornaments'),
    path('transactions/kaligarorder',KaligarorderListView.as_view(),name='kaligarorder'),
    # path('stocks/create',StockCreateView.as_view(),name='stock-create'),
    path('transaction_update/<int:pk>/',TransactionUpdateView.as_view(), name='transaction_update'),
    # path('deleted/', StockDeletedListView.as_view(), name='stocks_deleted'),
    # path('stock-restore/<int:pk>/', restore_stock, name='restore_stock'),,
]

templates/footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span>
    </div>
  </footer>

templates/navbar.html
{% load static %}
<nav class="navbar p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
      <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'admin/assets/images/logo-mini.svg' %}" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
      <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
        <span class="mdi mdi-menu"></span>
      </button>
      <ul class="navbar-nav w-100">
        <li class="nav-item w-100">
          <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
            <input type="text" class="form-control" placeholder="Search products">
          </form>
        </li>
      </ul>
      <ul class="navbar-nav navbar-nav-right">
        <li class="nav-item dropdown d-none d-lg-block">
          <a class="nav-link btn btn-success create-new-button" id="createbuttonDropdown" data-toggle="dropdown" aria-expanded="false" href="#">+ Create New Project</a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="createbuttonDropdown">
            <h6 class="p-3 mb-0">Projects</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-file-outline text-primary"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1">Software Development</p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-web text-info"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1">UI Development</p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-layers text-danger"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1">Software Testing</p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <p class="p-3 mb-0 text-center">See all projects</p>
          </div>
        </li>
        <li class="nav-item nav-settings d-none d-lg-block">
          <a class="nav-link" href="#">
            <i class="mdi mdi-view-grid"></i>
          </a>
        </li>
        <li class="nav-item dropdown border-left">
          <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
            <i class="mdi mdi-email"></i>
            <span class="count bg-success"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
            <h6 class="p-3 mb-0">Messages</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="assets/images/faces/face4.jpg" alt="image" class="rounded-circle profile-pic">
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1">Mark send you a message</p>
                <p class="text-muted mb-0"> 1 Minutes ago </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="assets/images/faces/face2.jpg" alt="image" class="rounded-circle profile-pic">
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1">Cregh send you a message</p>
                <p class="text-muted mb-0"> 15 Minutes ago </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="assets/images/faces/face3.jpg" alt="image" class="rounded-circle profile-pic">
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1">Profile picture updated</p>
                <p class="text-muted mb-0"> 18 Minutes ago </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <p class="p-3 mb-0 text-center">4 new messages</p>
          </div>
        </li>
        <li class="nav-item dropdown border-left">
          <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
            <i class="mdi mdi-bell"></i>
            <span class="count bg-danger"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
            <h6 class="p-3 mb-0">Notifications</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-calendar text-success"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject mb-1">Event today</p>
                <p class="text-muted ellipsis mb-0"> Just a reminder that you have an event today </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-settings text-danger"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject mb-1">Settings</p>
                <p class="text-muted ellipsis mb-0"> Update dashboard </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-link-variant text-warning"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject mb-1">Launch Admin</p>
                <p class="text-muted ellipsis mb-0"> New admin wow! </p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <p class="p-3 mb-0 text-center">See all notifications</p>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
            <div class="navbar-profile">
              <img class="img-xs rounded-circle" src="{% static 'admin/assets/images/faces/face15.jpg' %}" alt="">
              <p class="mb-0 d-none d-sm-block navbar-profile-name">{{ username }}</p>
              <i class="mdi mdi-menu-down d-none d-sm-block"></i>
            </div>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
            <h6 class="p-3 mb-0">Profile</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-settings text-success"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject mb-1">Settings</p>
              </div>
            </a>
            <div class="dropdown-divider"></div>

            <a href="{% url 'stocks:logout' %}" class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-logout text-danger"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject mb-1">Log out</p>
              </div>
            </a>

            
            <div class="dropdown-divider"></div>
            <p class="p-3 mb-0 text-center">Advanced settings</p>
          </div>
        </li>
      </ul>
      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="mdi mdi-format-line-spacing"></span>
      </button>
    </div>
  </nav>

templates/purchasesource.html
{% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}


        <div class="main-panel">
          <div class="content-wrapper" style="margin-bottom:0; padding-bottom:0;">

            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">

                    <h4 class="card-title">Upload Purchase Source</h4>
             
                    <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{ upload_form.non_field_errors }}

                      <div  class="form-group">
                        <div class="row">
                          <div class="col-3">{{ upload_form.purchase_file.label_tag }}</div>

                          <div class="col-3">{{ upload_form.purchase_file }} </div>

                          <div class="col-3">
                            {% if upload_form.purchase_file.errors %}
                              <div class="text-danger">
                                {% for error in upload_form.purchase_file.errors %}
                                  <span>{{ error }}</span><br>
                                {% endfor %}
                              </div>
                            {% endif %}
                          </div>

                        {% if message %}
                              <div class="text-danger">
                                  <span>{{ message }}</span><br>
                              </div>
                        {% endif %}
                    

                          <div class="col-3"><button type="submit" style="font-size:12.8px;" class="btn btn-success float-right">Upload Purchase Source</button></div>

                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          
        

            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                      <h4 class="card-title">{{ title }}</h4>

                      <button type="button"  class="btn btn-primary float-right mt-2" data-toggle="modal" data-target="#myModal"> Add purchase source</button>

                      <div class="btn-group" role="group" aria-label="Purchased From">
                        <a href="{% url 'stocks:purchasesource' %}" class="btn btn-secondary {% if not purchase_source %}active{% endif %}">All</a>
                        <a href="{% url 'stocks:purchasesource_deleted' %}" class="btn btn-secondary">Deleted</a>
                    </div>

                    <div class="table-responsive">
                      <table class="table"> 
                        <thead>
                          <tr style="color:white">
                            <th>Actions</th>
                            <th> Name</th>
                            <th> Pan </th>
                            <th> Total weight </th>
                            <th> Total </th>
                          </tr>
                        </thead>
                        <tbody>
              
                        
                          {% for item in purchase_source %}
                            <tr>
                              <td>
                    
                               <!-- Example Edit Button -->
                              {% comment %} <button class="btn btn-primary edit-button" data-purchase-id="{{ purchase_source.id }}">edit</button> {% endcomment %}
                                  <a href="{% url 'stocks:purchase-source_update' item.pk %}" class="btn btn-primary">edit</a>
                                  <a onclick="deleteItem(this)" data-id="{{ item.id }}" class="btn btn-danger">delete</a>
                              </td>
                              <td>
                                <span class="pl-2"><a href="{% url 'stocks:purchasesourcedetail' %}?purchased_from={{ item.id }}">{{ item.name }}</a></span>
                              </td>
                              <td>{{ item.pan }}</td>
                              <td>{{ item.total_weight|floatformat:0 }}</td>
                              <td>{{ item.total_amount|floatformat:0 }}</td>
                            </tr>

                            {% empty%}
                            <tr>
                                <td colspan="4">No sources found.</td>
                            </tr>

                            {% endfor %}
                            
                            {% comment %} {% if purchase_source %}
                            <tr style="color:white">
                              <td>Total Weight</td>
                              <td colspan=2""></th>
                              <td>{{ total_weight|floatformat:2 }}</td>
                              <td></td>
                              <td>{{ total|floatformat:0 }}</td>
                              <td>{{ paid|floatformat:0 }}</td>
                              <td>{{ due|floatformat:0 }}</td>
                              <td colspan=3""></th>
                            </tr>

                        {% endif %} {% endcomment %}

                          </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>

          {% include 'include/add_model.html' %}
          {% include 'footer.html' %}

          <!-- partial -->
        </div>

    {% endblock %}

templates/sidebar.html
{% load static %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
      <a class="sidebar-brand brand-logo" href="index.html"><img src="{% static 'admin/assets/images/logo.svg' %}" alt="logo" /></a>
      <a class="sidebar-brand brand-logo-mini" href="index.html"><img src="{% static 'admin/assets/images/logo-mini.svg' %}" alt="logo" /></a>
    </div>
    <ul class="nav">
      <li class="nav-item profile">
        <div class="profile-desc">
          <div class="profile-pic">
            <div class="count-indicator">
              <img class="img-xs rounded-circle " src="{% static 'admin/assets/images/faces/face15.jpg' %}" alt="">
              <span class="count bg-success"></span>
            </div>
            <div class="profile-name">
              <h5 class="mb-0 font-weight-normal">{{ username }}</h5>
              <span>{{ usertype }}</span>
            </div>
          </div>
          <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
          <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
            <a href="#" class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-settings text-primary"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1 text-small">Account settings</p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-onepassword  text-info"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
              </div>
            </a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-calendar-today text-success"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject ellipsis mb-1 text-small">To-do list</p>
              </div>
            </a>
          </div>
        </div>
      </li>
      <li class="nav-item nav-category">
        <span class="nav-link">Navigation</span>
      </li>
      <li class="nav-item menu-items">
        <a class="nav-link" href="{% url 'stocks:home' %}">
          <span class="menu-icon">
            <i class="mdi mdi-speedometer"></i>
          </span>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-purchase-source" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Misc</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-purchase-source">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:purchasesource' %}">Purchase source</a></li>
          </ul>
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'transaction:kaligarorder' %}">Kaligar</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-stocks" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Stocks</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-stocks">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:goldstocks' %}">Gold Stock</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:ornamentstock' %}">Gold Ornaments Stock</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:goldstocks' %}">Silver Stock</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:goldstocks' %}">Silver Ornaments Stock</a></li>
          </ul>
        </div>
      </li>

      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-ornament" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Ornaments</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-ornament">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:ornamentscount' %}">Ornaments List</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:ornaments' %}?material=Gold">Gold</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'stocks:ornaments' %}?material=Silver">Silver</a></li>
          </ul>
        </div>
      </li>

      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-order" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Order</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-order">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'sales:order' %}">Gold</a></li>
            <li class="nav-item"> <a class="nav-link" href="">Silver</a></li>
          </ul>
        </div>
      </li>

      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-sales" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Sales</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-sales">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'sales:sales' %}">Gold</a></li>
            <li class="nav-item"> <a class="nav-link" href="">Silver</a></li>
          </ul>
        </div>
      </li>

      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-investments" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Accounts</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-investments">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"><a class="nav-link" href="{% url 'investmentsandexpenses:summary' %}">Summary</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'investmentsandexpenses:capital' %}">Capital</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'investmentsandexpenses:investments' %}">Investment</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'investmentsandexpenses:expenses' %}">Expenses</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'transaction:transaction' %}">Transactions</a></li>
          </ul>
        </div>
      </li>

      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#ui-reports" aria-expanded="false" aria-controls="ui-basic">
          <span class="menu-icon">
            <i class="mdi mdi-laptop"></i>
          </span>
          <span class="menu-title">Reports and Analysis</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="ui-reports">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"><a class="nav-link" href="{% url 'investmentsandexpenses:expenses' %}">Profit and Loss Statement</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'investmentsandexpenses:investments' %}">Balance Sheet</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'transaction:transaction' %}">Cash Flow Statement</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'transaction:transaction' %}">Income vs. Expenses Chart</a></li>
          </ul>
        </div>
      </li>

      <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
          <span class="menu-icon">
            <i class="mdi mdi-security"></i>
          </span>
          <span class="menu-title">User Pages</span>
          <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="auth">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="pages/samples/blank-page.html"> Blank Page </a></li>
            <li class="nav-item"> <a class="nav-link" href="pages/samples/error-404.html"> 404 </a></li>
            <li class="nav-item"> <a class="nav-link" href="pages/samples/error-500.html"> 500 </a></li>
            <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>
            <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item menu-items">
        <a class="nav-link" href="http://www.bootstrapdash.com/demo/corona-free/jquery/documentation/documentation.html">
          <span class="menu-icon">
            <i class="mdi mdi-file-document-box"></i>
          </span>
          <span class="menu-title">Documentation</span>
        </a>
      </li>
    </ul>
  </nav>
  <!-- partial -->