jewellers/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    # path('',include('inventory.urls',namespace='inventory')),
    path('',include('inventory.urls')),
    path('',include('sales.urls')),
    path('',include('transaction.urls')),
    path('',include('investment.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import include, path

from .views import *
from .views import convert_orders_to_sales
app_name ='sales'

urlpatterns = [
    path('orders/',OrderView.as_view(),name='order'),
    path('order/create',OrderCreateView.as_view(),name='search_ornaments'),
    path('order/create',OrderCreateView.as_view(),name='order-create'),
    path('order_update/<int:pk>/',OrderUpdateView.as_view(), name='order_update'),
    path('sales/',SalesView.as_view(),name='sales'),
    path('sales/create',SalesCreateView.as_view(),name='sales-create'),
    path('sales_update/<int:pk>/',SalesUpdateView.as_view(), name='sales_update'),
    path('convert_order_to_sales/<int:order_id>/', convert_orders_to_sales, name='convert_order_to_sales'),
    # path('deleted/', StockDeletedListView.as_view(), name='sales_deleted'),
    # path('restore/<int:pk>/', restore_stock, name='restore_sales'),

]

sales/forms.py
from django import forms
from django.contrib.auth import get_user_model
from nepali_datetime_field.forms import NepaliDateField
from inventory.models import Ornaments
from .models import Sales, Order, SelectedOrnament
import nepali_datetime
from django_select2.forms import Select2MultipleWidget

User=get_user_model()

class SalesUploadForm(forms.Form):
    sales_file = forms.FileField(label='Upload Sales File', widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}))

    def clean_stock_file(self):
        sales_file = self.cleaned_data['sales_file']
        if sales_file:
            if not sales_file.name.endswith('.xlsx'):
                raise forms.ValidationError('Invalid file format. Please upload a valid Excel file.')
        return sales_file

class SearchOrnamentsWidget(Select2MultipleWidget):
    search_fields = [
        'product_name__icontains',
        'weight__icontains',
        'purity__icontains',
        'material__icontains',
    ]
      
          
class OrderForm(forms.ModelForm):
    selected_ornaments = forms.ModelMultipleChoiceField(
    queryset=SelectedOrnament.objects.filter(order_status='PROCESSING'),
    widget=SearchOrnamentsWidget(attrs={'style': 'width: 100%;'}),
    )

    class Meta:
        model = Order
        fields =['nepali_date','customer','address','phone_no','selected_ornaments','discounts','own_gold','cash','bank','due','notes']
        widgets = {
            'nepali_date': forms.DateInput(attrs={'class': 'form-control'}),
            'customer': forms.TextInput(attrs={'class': 'form-control','required': 'true'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_no': forms.TextInput(attrs={'class': 'form-control'}),
            'discounts': forms.TextInput(attrs={'class': 'form-control'}),
            'own_gold': forms.TextInput(attrs={'class': 'form-control'}),
            'cash': forms.TextInput(attrs={'class': 'form-control'}),
            'bank': forms.TextInput(attrs={'class': 'form-control'}),
            'due': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control'}),
        }
        date:NepaliDateField()   


    def label_from_instance(self, obj):
            return f"{obj.product_name} - Weight: {obj.weight} - Purity: {obj.purity} - Material: {obj.material}"    
     
     
    def __init__(self,*args,**kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        nepali_date=nepali_datetime.date.today()
        self.fields['nepali_date'].initial = nepali_date


class selectedOrnamentForm(forms.ModelForm):

    class Meta:
        model=SelectedOrnament
        fields=['ornament','rate','jarti','jyala','stone']
        widgets={
            'ornament': forms.Select(attrs={'class': 'form-control col-12'}),
            'rate': forms.TextInput(attrs={'class': 'form-control'}),
            'jarti': forms.TextInput(attrs={'class': 'form-control'}),
            'jyala': forms.TextInput(attrs={'class': 'form-control'}),
            'stone': forms.TextInput(attrs={'class': 'form-control'}),
        }
   
    def __init__(self, *args, **kwargs):
        super(selectedOrnamentForm, self).__init__(*args, **kwargs)
        
        # Modify the queryset for the 'ornament' field to only show available ornaments
        available_ornaments = Ornaments.objects.filter(stock='AVAILABLE').order_by('product_name')  # Adjust the filter criteria as needed
        self.fields['ornament'].queryset = available_ornaments
    
class SalesForm(forms.ModelForm):
    
    selected_ornaments = forms.ModelMultipleChoiceField(
    queryset=SelectedOrnament.objects.filter(order_status='PROCESSING'),
    widget=SearchOrnamentsWidget(attrs={'style': 'width: 100%;'}),
    )
    
    class Meta:
        model = Sales
        fields = ['bill_no','nepali_date','customer','address','phone_no','selected_ornaments','own_gold','discounts','total_weight','grand_total','profit','cash','bank','due','notes']
        widgets = {
            'bill_no': forms.TextInput(attrs={'class': 'form-control'}),
            'nepali_date': forms.DateInput(attrs={'class': 'form-control'}),
            'customer': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_no': forms.TextInput(attrs={'class': 'form-control'}),
            'discounts': forms.TextInput(attrs={'class': 'form-control'}),
            'own_gold': forms.TextInput(attrs={'class': 'form-control'}),
            'cash': forms.TextInput(attrs={'class': 'form-control'}),
            'bank': forms.TextInput(attrs={'class': 'form-control'}),
            'due': forms.TextInput(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control'}),
            'total_weight': forms.TextInput(attrs={'class': 'form-control'}),
            'grand_total': forms.TextInput(attrs={'class': 'form-control'}),
            'profit': forms.TextInput(attrs={'class': 'form-control'}),
        }
        date:NepaliDateField()
        
    def label_from_instance(self, obj):
            return f"{obj.product_name} - Weight: {obj.weight} - Purity: {obj.purity} - Material: {obj.material}"
        
    def __init__(self,*args,**kwargs):
        super(SalesForm, self).__init__(*args, **kwargs)
        nepali_date=nepali_datetime.date.today()
        self.fields['nepali_date'].initial = nepali_date

        



templates/order/order.html
{% extends 'basic.html' %}
{% load static %}



<!-- container-scroller -->
{% block body %}

        <div class="main-panel">
          <div class="content-wrapper">


            <div class="row">
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ gold_sales }} gram</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success ">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Gold Sales</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">Rs. {{ total_sales }}</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+11%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Total sales</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">{{ mix_gold}}</h3>
                          <p class="text-danger ml-2 mb-0 font-weight-medium">-2.4%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-danger">
                          <span class="mdi mdi-arrow-bottom-left icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Mix Gold</h6>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-sm-6 grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <div class="row">
                      <div class="col-9">
                        <div class="d-flex align-items-center align-self-start">
                          <h3 class="mb-0">$31.53</h3>
                          <p class="text-success ml-2 mb-0 font-weight-medium">+3.5%</p>
                        </div>
                      </div>
                      <div class="col-3">
                        <div class="icon icon-box-success ">
                          <span class="mdi mdi-arrow-top-right icon-item"></span>
                        </div>
                      </div>
                    </div>
                    <h6 class="text-muted font-weight-normal">Expense current</h6>
                  </div>
                </div>
              </div>
            </div>
          
            <div class="row ">
              <div class="col-12 grid-margin">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">{{ title }}</h4>
             
                    <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      {{ sales_upload_form.non_field_errors }}
                      <div class="row">
                        {% if message %}
                              <div class="text-danger">
                                  <span>{{ message }}</span><br>
                              </div>
                        {% endif %}
                      </div>
                      
                      <div class="form-group">
                        <div class="row">
                          <div class="col-3">
                          {{ sales_upload_form.sales_file.label_tag }}
                          </div>

                          <div class="col-3">
                            {{ sales_upload_form.sales_file }}
                          </div>

                          <div class="col-3">
                            {% if sales_upload_form.sales_file.errors %}
                              <div class="text-danger">
                                {% for error in sales_upload_form.sales_file.errors %}
                                    <span>{{ error }}</span><br>
                                {% endfor %}
                              </div>
                            {% endif %}
                          </div>

                         

                        </div>
                      </div>    
                    </form>

                  
              <a href="{% url 'sales:order-create' %}" class="btn btn-primary float-right">Add New Order</a>

              <div class="btn-group" role="group" aria-label="ORDERS">
                <a href="{% url 'sales:order' %}" class="btn btn-secondary {% if not order_status %}active{% endif %}">All</a>
                <a href="{% url 'sales:order' %}?order=created" class="btn btn-secondary {% if order_status == 'created' %}active{% endif %}">Created</a>
                <a href="{% url 'sales:order' %}?order=processing" class="btn btn-secondary {% if order_status == 'processing' %}active{% endif %}">Processing</a>
                <a href="{% url 'sales:order' %}?order=completed" class="btn btn-secondary {% if order_status == 'completed' %}active{% endif %}">Completed</a>
                <a href="{% url 'sales:order' %}?order=cancelled" class="btn btn-secondary {% if order_status == 'cancelled' %}active{% endif %}">Cancelled</a>
                <a href="{% url 'sales:order' %}" class="btn btn-secondary">Deleted</a>
            </div> 

                    <div class="table-responsive">
                      <table class="table"> 
                        <thead>
                          <tr style="color:white">
                            
                            <th> Date </th>
                            <th> Customer </th>
                            {% comment %} <th> Address </th> {% endcomment %}
                            <th> Phone no </th>
                            <th> Ornaments </th>
                            {% comment %} <th> Material </th> {% endcomment %}
                            <th> Total Weight </th>
                            <th> Rate </th>
                            <th> Grand total </th>
                            <th> Cash </th>
                            <th> Bank </th>
                            <th> Due </th>
                            <th> Notes </th>
                            <th>Actions</th>
                          </tr>
                        </thead>
                        <tbody>
              
                        
                          {% for item in order %}
                            <tr>
                              <td>{{ item.nepali_date }}</td>
                              <td>{{ item.customer }}</td>
                              {% comment %} <td>{{ item.address }}</td> {% endcomment %}
                              <td>{{ item.phone_no }}</td>
                              <td>
                              {% for item in item.selected_ornaments.all %}
                              {{ item.ornament.product_name }}
                              {% endfor %}
                              </td>

                              <td> {{ item.total_weight|floatformat:2 }} </td>
                              <td> {{ item.rate|floatformat:0 }} </td>
                              <td> {{ item.grand_total|floatformat:2 }} </td>
                              <td> {{ item.cash|floatformat:2 }} </td>
                              <td> {{ item.bank|floatformat:2 }} </td>
                              <td>{{ item.due }}</td>
                              <td>{{ item.notes }}</td>
                              <td>
                    
                                <a href="{% url 'sales:order_update' item.pk %}" class="btn btn-primary" >edit</a>

                               
                                  {% if item.order_status != 'completed' %}
                                  <a href="{% url 'sales:convert_order_to_sales' item.id %}" class="btn btn-primary">Convert to Sales</a>
                                  {% else %}
                                    Converted to Sales
                                  {% endif %}
                                

                                  <a onclick="deleteItem(this)" data-id="{{ item.id }}" class="btn btn-danger">delete</a>
                              </td>
                            
                            {% empty%}
                            <tr>
                                <td colspan="4">No orders found.</td>
                            </tr>

                            {% endfor %}
                          
                            {% if stocks%}
                            <tr style="color:white">
                              <td>Total Weight</td>
                              <td colspan=2""></th>
                              <td>{{ totalweight|floatformat:2 }}</td>
                              <td></td>
                              <td>{{ total|floatformat:0 }}</td>
                              <td>{{ paid|floatformat:0 }}</td>
                              <td>{{ due|floatformat:0 }}</td>
                              <td colspan=3""></th>
                            </tr>

                        {% endif %}
                          </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>


          {% include 'footer.html' %}

          <!-- partial -->
        </div>

    {% endblock %}

templates/order/order_create.html
{% extends 'basic.html' %}
{% load static %}


{% block body %}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">       
            <div class="col-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add</h4>

                            <!-- Button to Open the Modal -->
          
                        <form method="POST" class="card-body" enctype="multipart/form-data">
                            {% csrf_token %}
                          
                             
                            <div class="row">
                                

                                <div class="fieldWrapper col-6">
                                    <div class="form-group">
                                        {{ orderform.nepali_date.label_tag }}
                                        {{ orderform.nepali_date }}
                                    </div>
                                </div>

                                <div class="fieldWrapper col-6">
                                    <div class="form-group">
                                        {{ orderform.customer.label_tag }}
                                        {{ orderform.customer }}
                                    </div>
                                </div>

                                <div class="fieldWrapper col-6">
                                    <div class="form-group">
                                        {{ orderform.address.label_tag }}
                                        {{ orderform.address }}
                                    </div>
                                </div>

                                <div class="fieldWrapper col-6">
                                    <div class="form-group">
                                        {{ orderform.phone_no.label_tag }}
                                        {{ orderform.phone_no }}
                                    </div>
                                </div>

                                
                                <div class="fieldWrapper col-6">
                                    <div class="form-group">
                                        {{ orderform.selected_ornaments.label_tag }} 
                                        {{ orderform.selected_ornaments }}
                                    </div>
                                </div>

                                <div class="fieldWrapper col-3">
                                    <div class="form-group">
                                  <!-- Add New button outside the custom dropdown -->
                                  <button class="mt-4 btn btn-primary" data-toggle="modal" data-target="#selectModal">Select Existing</button>
                                  
                                    </div>
                                </div>

                                <div class="fieldWrapper col-3">
                                    <div class="form-group">
                                  <!-- Add New button outside the custom dropdown -->
                                  <button class="mt-4 btn btn-success" data-toggle="modal" data-target="#selectModal">Add New</button>
                                  
                                    </div>
                                </div>

                                <div class="table-responsive">
                                    <table class="mt-2 mb-4 table">
                                        <thead>
                                            <tr style="color:white">
                                                <th>Product</th>
                                                <th>Purity</th>
                                                <th>Weight</th>
                                                <th>Rate</th>
                                                <th>Jarti</th>
                                                <th>Jyala</th>
                                                <th>Stone</th>
                                                <th>Total</th>
                                            </tr>
                                        </thead>
                                        <tbody id="selectedOrnamentsTable">
                                            <!-- Selected ornament rows will be added here dynamically -->

                                        
                                            <tr>
                                                <td colspan="4">No ornaments selected.</td>
                                            </tr>


                                            <tr style="color:white">
                                            <td>Total Weight</td>
                                            <td colspan=2""></th>
                                            <td></td>
                                            <td colspan=3""></th>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>



                                <div class="fieldWrapper col-3">
                                    <div class="form-group">
                                        {{ orderform.own_gold.label_tag }}
                                        {{ orderform.own_gold }}
                                    </div>
                                </div>


                                <div class="fieldWrapper col-3">
                                    <div class="form-group">
                                        {{ orderform.cash.label_tag }}
                                        {{ orderform.cash }}
                                    </div>
                                </div>

                                <div class="fieldWrapper col-3">
                                    <div class="form-group">
                                        {{ orderform.bank.label_tag }}
                                        {{ orderform.bank }}
                                    </div>
                                </div>

                                <div class="fieldWrapper col-3">
                                    <div class="form-group">
                                        {{ orderform.discounts.label_tag }}
                                        {{ orderform.discounts }}
                                    </div>
                                </div>


                                <div class="fieldWrapper col-12">
                                    <div class="form-group">
                                        {{ orderform.notes.label_tag }}
                                        {{ orderform.notes }}
                                    </div>
                                </div>
                               
                                
                            </div>
                          
                        
                          <button type="submit" class="btn btn-primary">Save Order</button>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


    {% include 'include/add_model.html' %}
    {% include 'include/select_model.html' %}
    {% include 'footer.html' %}

    
    <script>
        $(document).ready(function() {
            $('#id_selected_ornaments').select2();

            $('#id_selected_ornaments').on('change', function() {
                var selectedOrnaments = $(this).val();

            //Clear the table body
            var tableBody=$('.table tbody');
            tableBody.empty();
            var total_weight=0;
            var grand_total=0;
            var total_jarti=0;
            var total_jyala=0;
            var total_stone=0;

            // Iterate through the selected ornaments and add rows to the table
            if (selectedOrnaments && selectedOrnaments.length > 0) {
                for (var i = 0; i < selectedOrnaments.length; i++) {
                    var ornament = $('#id_selected_ornaments option[value="' + selectedOrnaments[i] + '"]').text();
                    // Split the text into an array of substrings using hyphen as the delimiter
                    var parts = ornament.split(' - ');

                    // Initialize an object to store the values
                    var ornamentData = {};

                    // Iterate through the parts and split each part based on colon
                    parts.forEach(function(part) {
                        var keyValue = part.split(':');
                        var key = keyValue[0].trim();
                        var value = keyValue[1].trim();

                        // Assign values to the object based on the keys
                        ornamentData[key] = value;
                    });

                    // Convert the object to a JSON string
                    var ornamentJson = JSON.stringify(ornamentData);

                    var total = parseFloat(ornamentData["Total"]); // Convert the value to a float before adding
                    var weight= parseFloat(ornamentData["Weight"])
                    var jarti= parseFloat(ornamentData["Jarti"])
                    var jyala= parseFloat(ornamentData["Jyala"])
                    var stone= parseFloat(ornamentData["Stone"])
                    grand_total+=total
                    total_weight+=weight
                    total_jarti+=jarti
                    total_jyala+=jyala
                    total_stone+=stone
                    
                    var newRow = $('<tr>');
                    newRow.append($('<td>').text(ornamentData["Name"]));
                    newRow.append($('<td>').text(ornamentData["Purity"]));
                    newRow.append($('<td>').text(ornamentData["Weight"]));
                    newRow.append($('<td>').text(ornamentData["Rate"]));
                    newRow.append($('<td>').text(ornamentData["Jarti"]));
                    newRow.append($('<td>').text(ornamentData["Jyala"]));
                    newRow.append($('<td>').text(ornamentData["Stone"]));
                    newRow.append($('<td>').text(total)); // Replace with the actual stone value
                    
                    tableBody.append(newRow);
                }
            }
            var newRow = $('<tr>');
            newRow.append($('<td>').text('Grand total'));
            newRow.append($('<td>').text(''));
            newRow.append($('<td>').text(total_weight));
            newRow.append($('<td>').text('')); 
            newRow.append($('<td>').text(total_jarti));
            newRow.append($('<td>').text(total_jyala));
            newRow.append($('<td>').text(total_stone));
            newRow.append($('<td>').text(grand_total)); // Replace with the actual stone value
            tableBody.append(newRow);
           




            });
        });

    </script>
    
    
</div>
{% endblock %}

templates/order/order_update.html
{% extends 'basic.html' %}
{% load static %}

{% block body %}
  <h2>Update Ornament</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Update Ornament</button>
  </form>
{% endblock %}

    {% include 'footer.html' %}
</div>